package com.voicebuilder.resume.entity;

import lombok.Data;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

@Data
@Document(collection = "voice_sessions")
public class VoiceSession {
    
    @Id
    private String id;
    
    private String userId;      // The user who uploaded this audio
    private String resumeId;    // The resume this audio belongs to
    
    private String originalFileName;
    private String savedFilePath;
    private long fileSize;
    
    // The final text returned from Groq Whisper AI
    private String transcribedText;
    
    // Status tracking for our AI Agents (Pending, Transcribing, Processing, Completed, Failed)
    private String status = "UPLOADED";
    
    // The TTS feedback generated by AI identifying missing fields
    private String aiFeedback;
    
    private LocalDateTime uploadedAt = LocalDateTime.now();
    private LocalDateTime updatedAt = LocalDateTime.now();
}
