spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  application:
    name: resume-builder
  data:
    mongodb:
      # Replace the string below with your actual MongoDB URI
      uri: ${MONGO_URI:mongodb://localhost:27017/resume_builder}

server:
  port: 8080

groq:
  api:
    key: ${GROQ_API_KEY:your_api_key_here}

    whisper-url: https://api.groq.com/openai/v1/audio/transcriptions
    llama-url: https://api.groq.com/openai/v1/chat/completions
